services:
  - type: web
    name: smchess-mcp-server
    runtime: python
    buildCommand: uv sync
    startCommand: uv run python -m src.server
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: MCP_TRANSPORT
        value: http
